name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Raspberry Pi
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} {{ secrets.RASPBERRY_PI_USER }}@${{ secrets.RASPBERRY_PI_IP }} -p ${{ secrets.RASPBERRY_PI_PORT }}"cd /path/to/your/project && git pull"

