name: Connect to Raspberry Pi

on:
  push:
    branches:
      - main  # Adjust this to your main branch name
  workflow_dispatch: 

jobs:
  connect-to-pi:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Connect to Raspberry Pi
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.RASPBERRY_PI_IP }}
          username: ${{ secrets.RASPBERRY_PI_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.RASPBERRY_PI_PORT }}
          script: |
            cd /home/docker/stacks/blog
            git pull https://github.com/LukasOlivier/blog.git
            docker compose build --no-cache react-blog
            docker compose stop react-blog
            docker compose up -d react-blog
