name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main  # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
                  - name: Action-SSH
                    # You may pin to the exact commit or the version.
                    # uses: tiyee/action-ssh@b2d48d44e978ff09e0c37479a429a8374da6bb63
                    uses: tiyee/action-ssh@v1.0.1
                    with:
                      # Command to execute on the remote server.
                      command: 'ls -la'
                      # Hostname or IP address of the server.
                      host: '141.134.173.203'
                      # Username for authentication.
                      username: 'raspberry'
                      # Port number of the server.
                      port: '22'
                      # File  string that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
                      privateKey: "${{ secrets.SSH_KEY }}"
          
