name: Connect to Raspberry Pi

on:
  # Trigger on push events to the main branch
  push:
    branches: [ main ]

jobs:
  connect-to-pi:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Connect to Raspberry Pi
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.RASPBERRY_PI_IP }}
          port: ${{ secrets.RASPBERRY_PI_PORT }}
          username: ${{ secrets.RASPBERRY_PI_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/docker/stacks/blog
            git pull https://github.com/LukasOlivier/blog.git
